In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ai-w3p1/train.csv
/kaggle/input/2022-ai-w3p1/test.csv
/kaggle/input/2022-ai-w3p1/submit_sample.csv


In [2]:
train_data = pd.read_csv('/kaggle/input/2022-ai-w3p1/train.csv')
test_data = pd.read_csv('/kaggle/input/2022-ai-w3p1/test.csv')
sample_data = pd.read_csv('/kaggle/input/2022-ai-w3p1/submit_sample.csv')

In [3]:
train_y = train_data['avgPrice']
train_y

0       2123
1       2123
2       2123
3       2020
4       2060
        ... 
2552    4226
2553    4200
2554    4224
2555    4219
2556    4219
Name: avgPrice, Length: 2557, dtype: int64

In [4]:
train_x = train_data.drop(['avgPrice','year'], axis = 1)
train_x

avgTemp  minTemp  maxTemp  rainFall
0        -4.9    -11.0      0.9       0.0
1        -3.1     -5.5      5.5       0.8
2        -2.9     -6.9      1.4       0.0
3        -1.8     -5.1      2.2       5.9
4        -5.2     -8.7     -1.8       0.7
...       ...      ...      ...       ...
2552      1.2     -3.2      4.5       2.1
2553     -1.4     -6.5      4.8       0.0
2554     -1.3     -4.5      2.1       0.2
2555     -1.4     -7.0      4.6       0.0
2556      1.7     -2.9      7.1       0.0

[2557 rows x 4 columns]

In [5]:
import torch
import torch.optim as optim

In [6]:
torch.manual_seed(1)

In [7]:
train_x.values

array([[ -4.9, -11. ,   0.9,   0. ],
       [ -3.1,  -5.5,   5.5,   0.8],
       [ -2.9,  -6.9,   1.4,   0. ],
       ...,
       [ -1.3,  -4.5,   2.1,   0.2],
       [ -1.4,  -7. ,   4.6,   0. ],
       [  1.7,  -2.9,   7.1,   0. ]])

In [8]:
x_train = torch.FloatTensor(train_x.values)

In [9]:
x_test = torch.FloatTensor(test_data.drop('year', axis = 1).values)
x_test

tensor([[ 4.0000, -1.4000,  9.5000,  0.1000],
        [-1.7000, -5.4000,  1.4000,  3.3000],
        [ 1.4000, -2.0000,  5.0000,  0.0000],
        [ 3.6000, -2.5000, 11.1000,  0.1000],
        [ 5.0000, -1.6000, 11.3000,  0.0000],
        [ 7.3000,  0.7000, 13.6000,  0.7000],
        [12.3000,  7.2000, 17.7000,  0.0000],
        [19.8000, 11.9000, 27.7000,  0.0000],
        [17.5000, 12.3000, 24.5000,  2.9000],
        [20.6000, 11.8000, 28.3000,  0.0000],
        [18.4000, 15.9000, 21.2000,  5.5000],
        [24.7000, 18.6000, 31.5000,  0.0000],
        [26.1000, 24.1000, 28.5000, 26.7000],
        [26.0000, 22.2000, 30.2000, 11.3000],
        [25.6000, 23.5000, 28.4000, 11.6000],
        [23.2000, 17.9000, 29.6000,  0.0000],
        [21.3000, 16.0000, 27.6000,  0.0000],
        [17.3000,  9.9000, 25.9000,  0.0000],
        [20.4000, 16.3000, 26.5000,  0.0000],
        [12.7000,  6.9000, 19.5000,  0.0000],
        [ 5.5000,  1.2000, 10.3000,  0.0000],
        [ 5.3000,  0.1000, 10.7000

In [10]:
y_train = torch.FloatTensor(train_y.values)
y_train

tensor([2123., 2123., 2123.,  ..., 4224., 4219., 4219.])

In [11]:
# x1_train = torch.FloatTensor(train_x['avgTemp'])
# x2_train = torch.FloatTensor(train_x['minTemp'])
# x3_train = torch.FloatTensor(train_x['maxTemp'])
# x4_train = torch.FloatTensor(train_x['rainFall'])
# x5_train = torch.FloatTensor(train_x['year'])

# y_train = torch.FloatTensor(train_y)
# x1_train

In [12]:
# 모델 초기화

W = torch.zeros((4, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-3)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    # Matrix 연산!!
    hypothesis = x_train.matmul(W) + b # or .mm or @

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    
    if epoch %100==0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))# 모델 초기화


Epoch    0/2000 hypothesis: tensor([0., 0., 0.,  ..., 0., 0., 0.]) Cost: 12013343.000000
Epoch  100/2000 hypothesis: tensor([2830.8247, 2793.9939, 2018.8015,  ..., 1655.0349, 2861.5024,
        2561.2146]) Cost: 2373769.000000
Epoch  200/2000 hypothesis: tensor([2861.5107, 2846.5940, 2052.1277,  ..., 1687.2205, 2889.8330,
        2587.9204]) Cost: 2359780.000000
Epoch  300/2000 hypothesis: tensor([2863.4580, 2875.1233, 2065.8447,  ..., 1704.6511, 2893.8989,
        2596.8208]) Cost: 2346367.000000
Epoch  400/2000 hypothesis: tensor([2865.1812, 2902.6282, 2079.2190,  ..., 1721.7421, 2897.7041,
        2605.4270]) Cost: 2333321.250000
Epoch  500/2000 hypothesis: tensor([2866.9209, 2929.3237, 2092.4160,  ..., 1738.6179, 2901.4529,
        2613.8906]) Cost: 2320630.750000
Epoch  600/2000 hypothesis: tensor([2868.6790, 2955.2322, 2105.4409,  ..., 1755.2837, 2905.1484,
        2622.2156]) Cost: 2308284.000000
Epoch  700/2000 hypothesis: tensor([2870.4536, 2980.3716, 2118.2949,  ..., 1771.741

In [13]:
# w1 = torch.zeros(1, requires_grad=True)
# w2 = torch.zeros(1, requires_grad=True)
# w3 = torch.zeros(1, requires_grad=True)
# w4 = torch.zeros(1, requires_grad=True)
# b = torch.zeros(1, requires_grad=True)


# # optimizer 설정
# optimizer = optim.SGD([w1, w2, w3, w4, b], lr=1e-5)

# nb_epochs = 1000
# for epoch in range(1000 + 1):
    
#     # H(x) 계산
#     hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + x4_train * w4 +b

#     # cost 계산
#     cost = torch.mean((hypothesis - y_train) ** 2)

#     # cost로 H(x) 개선
#     optimizer.zero_grad()
#     cost.backward()
#     optimizer.step()

#     # 100번마다 로그 출력
#     if epoch % 100 == 0:
        
#         print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
#             epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
#         ))

In [14]:
y_pred = x_test.matmul(W) + b
y_pred

tensor([[2897.8574],
        [2047.2784],
        [2090.2358],
        [3511.5947],
        [3275.6665],
        [3342.4067],
        [2986.0322],
        [4141.5000],
        [3621.4585],
        [4214.5234],
        [2269.2617],
        [3716.3022],
        [2961.3442],
        [3142.8828],
        [2560.7783],
        [3482.2036],
        [3419.8940],
        [4219.8184],
        [3200.9312],
        [3454.3979],
        [2599.2217],
        [2884.2256],
        [3143.4590],
        [1925.6448]], grad_fn=<AddBackward0>)

In [15]:
submit = pd.DataFrame()

submit['id'] = pd.Series(range(len(y_pred)))
submit['Expected'] = y_pred.detach().numpy()
submit.to_csv('submit.csv', index = None)

In [16]:
submit

id     Expected
0    0  2897.857422
1    1  2047.278442
2    2  2090.235840
3    3  3511.594727
4    4  3275.666504
5    5  3342.406738
6    6  2986.032227
7    7  4141.500000
8    8  3621.458496
9    9  4214.523438
10  10  2269.261719
11  11  3716.302246
12  12  2961.344238
13  13  3142.882812
14  14  2560.778320
15  15  3482.203613
16  16  3419.894043
17  17  4219.818359
18  18  3200.931152
19  19  3454.397949
20  20  2599.221680
21  21  2884.225586
22  22  3143.458984
23  23  1925.644775

In [17]:
submit

id     Expected
0    0  2897.857422
1    1  2047.278442
2    2  2090.235840
3    3  3511.594727
4    4  3275.666504
5    5  3342.406738
6    6  2986.032227
7    7  4141.500000
8    8  3621.458496
9    9  4214.523438
10  10  2269.261719
11  11  3716.302246
12  12  2961.344238
13  13  3142.882812
14  14  2560.778320
15  15  3482.203613
16  16  3419.894043
17  17  4219.818359
18  18  3200.931152
19  19  3454.397949
20  20  2599.221680
21  21  2884.225586
22  22  3143.458984
23  23  1925.644775