In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ai-w5p1/train.csv
/kaggle/input/2022-ai-w5p1/test.csv
/kaggle/input/2022-ai-w5p1/sample_submit.csv


In [2]:
train_data = pd.read_csv('/kaggle/input/2022-ai-w5p1/train.csv')
test_data = pd.read_csv('/kaggle/input/2022-ai-w5p1/test.csv')
sample_data = pd.read_csv('/kaggle/input/2022-ai-w5p1/sample_submit.csv')

In [3]:
sample_data

id  label
0         1    NaN
1         2    NaN
2         3    NaN
3         4    NaN
4         5    NaN
...     ...    ...
9995   9996    NaN
9996   9997    NaN
9997   9998    NaN
9998   9999    NaN
9999  10000    NaN

[10000 rows x 2 columns]

In [4]:
train_data

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          3    0    0    0    0    0    0    0    0    0  ...      0      0   
3          3    0    0    0    0    0    0    0    0    0  ...      0      0   
4          6    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      0    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      9    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      4    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [5]:
train_y = train_data['label']
train_x = train_data.drop('label', axis = 1)
train_x

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0        0    0    0    0    0    0    0    0    0     0  ...      0      0   
1        0    0    0    0    0    0    0    0    0     0  ...      0      0   
2        0    0    0    0    0    0    0    0    0     0  ...      0      0   
3        0    0    0    0    0    0    0    0    0     0  ...      0      0   
4        0    0    0    0    0    0    0    0    0     0  ...      0      0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
59995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 784 columns]

In [6]:
import torch
import torch.optim as optim

torch.manual_seed(1)
x_train = torch.FloatTensor(train_x.values)
x_test = torch.FloatTensor(test_data.values)
y_train = torch.LongTensor(train_y.values)


y_train

tensor([5, 0, 3,  ..., 9, 4, 6])

In [7]:
x_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [8]:
nb_class = 10
nb_data = len(y_train)

y_one_hot = torch.zeros(nb_data, nb_class)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)

print(y_one_hot)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [9]:
import torch.nn.functional as F  # for softmax

nb_class = 10
nb_data = len(y_train)

W = torch.zeros((784, nb_class), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.00001)
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # Cost 계산 (1)
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) # or .mm or @
    
#     print(hypothesis.shape)
#     print(y_one_hot.shape)
    

#     cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
    
    # cost 표현법 2번 예시
    # cross_entropy를 사용하면 scatter 함수를 이용한 one_hot_encoding을 안해도 됨
    cost = F.cross_entropy((x_train.matmul(W) + b), y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 200 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 2.302585
Epoch  200/2000 Cost: 0.338156
Epoch  400/2000 Cost: 0.310511
Epoch  600/2000 Cost: 0.298011
Epoch  800/2000 Cost: 0.290351
Epoch 1000/2000 Cost: 0.284958
Epoch 1200/2000 Cost: 0.280853
Epoch 1400/2000 Cost: 0.277567
Epoch 1600/2000 Cost: 0.274846
Epoch 1800/2000 Cost: 0.272533
Epoch 2000/2000 Cost: 0.270531


In [10]:
hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
predict = torch.argmax(hypothesis, dim=1)
print(hypothesis)
print(predict)

tensor([[5.3108e-06, 1.5941e-03, 2.3174e-04,  ..., 3.2062e-05, 1.3038e-01,
         2.6088e-05],
        [9.9239e-01, 4.7847e-10, 9.3758e-07,  ..., 8.6460e-08, 6.1399e-06,
         8.7306e-08],
        [1.3206e-05, 4.9001e-06, 4.7781e-04,  ..., 1.2857e-06, 1.8676e-03,
         2.4258e-04],
        ...,
        [1.8152e-08, 2.4566e-04, 3.1172e-05,  ..., 1.0275e-01, 1.7766e-02,
         8.5522e-01],
        [2.3042e-02, 3.2800e-07, 6.0149e-02,  ..., 7.6123e-05, 2.4957e-02,
         3.2339e-03],
        [2.2328e-04, 3.7260e-05, 1.7246e-03,  ..., 1.5384e-07, 1.3320e-02,
         6.5491e-04]], grad_fn=<SoftmaxBackward0>)
tensor([5, 0, 3,  ..., 9, 6, 6])


In [11]:
hypothesis = F.softmax(x_test.matmul(W) + b, dim=1)
predict = torch.argmax(hypothesis, dim=1)
print(hypothesis)
print(predict)

tensor([[2.1849e-06, 2.7735e-08, 1.8984e-03,  ..., 1.1971e-05, 6.3409e-05,
         9.9953e-04],
        [6.7317e-09, 9.9125e-01, 1.5373e-04,  ..., 9.1027e-05, 1.2565e-03,
         8.5375e-04],
        [9.9974e-01, 8.1114e-14, 2.2040e-07,  ..., 1.7397e-10, 3.0454e-07,
         1.2470e-09],
        ...,
        [1.7577e-08, 4.6244e-09, 9.9913e-01,  ..., 1.6790e-11, 4.4222e-06,
         3.5398e-07],
        [7.0337e-04, 4.8991e-05, 8.6433e-03,  ..., 4.8886e-09, 9.7013e-01,
         1.1305e-06],
        [6.3920e-03, 3.4888e-05, 5.7430e-04,  ..., 2.7270e-02, 2.1271e-02,
         4.1802e-02]], grad_fn=<SoftmaxBackward0>)
tensor([6, 1, 0,  ..., 2, 8, 3])


In [12]:
len(predict)

10000

In [13]:

sample_data['label'] = predict.detach().numpy()

sample_data

id  label
0         1      6
1         2      1
2         3      0
3         4      0
4         5      9
...     ...    ...
9995   9996      3
9996   9997      7
9997   9998      2
9998   9999      8
9999  10000      3

[10000 rows x 2 columns]

In [14]:
sample_data.to_csv('submit.csv', index = None)